### ISSUE TITLE
Possibility to select date

### ISSUE THREAD

**Issue by kristian-lesko** [Dominick1993/GDLunch#31]
Hi,

would it be possible to add an option to select the date for which the menu should be displayed (e.g., tomorrow's menu in addition to today's one)? Thanks a lot :)

**Comment by Dominick1993** [comment]
Hi, thanks for the issue on GitHub 😁

Nice idea, it certainly would be possible, there would be just a smaller subset of restaurants, because some provide menus only on daily basis. I'll look into it for sure.

**Comment by Dominick1993** [comment]
Implemented & deployed

**Comment by kristian-lesko** [comment]
Great, thanks a lot! 👍
